<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>文件上传-测试</title>
</head>
<body>
<form id="login_form" action="/upload/doupload" method="post" enctype="multipart/form-data">
    <label for="file">Filename:</label>
    <input type="file" name="file" id="file" />
    <input type="file" name="file2" id="file2" />
    <br />
    <input type="submit" name="submit" value="Submit" />
</form>
</body>
</html>

